/**
 * Referral Token Utility
 *
 * Logistics providers can only sign up via a referral link generated by
 * a verified vendor or brand owner. This module handles token generation,
 * validation, and URL construction.
 *
 * NOTE: In production, tokens should be server-generated, stored in the DB,
 * and signed with a secret (e.g. JWT). This client-side approach is for
 * development / demo purposes and matches the rest of the codebase pattern.
 */

export interface ReferralPayload {
  /** The ID of the vendor or brand who generated the invite */
  referrerId: string;
  /** The role of the referrer — only 'vendor' and 'brand' are valid */
  referrerRole: 'vendor' | 'brand';
  /** Display name of the referrer shown on the signup page */
  referrerName: string;
  /** Purpose of this token (only 'logistics' is currently supported) */
  type: 'logistics';
  /** Issued-at timestamp (ms) */
  iat: number;
  /** Expiry timestamp (ms) — defaults to 7 days from issue */
  exp: number;
}

export interface ReferralValidationResult {
  valid: boolean;
  payload?: ReferralPayload;
  error?: string;
}

/** Validity window: 7 days */
const TOKEN_VALIDITY_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Generate a base64-encoded referral token.
 * Should only be called in the browser (uses window.btoa).
 */
export function generateReferralToken(
  referrerId: string,
  referrerRole: 'vendor' | 'brand',
  referrerName: string
): string {
  const payload: ReferralPayload = {
    referrerId,
    referrerRole,
    referrerName,
    type: 'logistics',
    iat: Date.now(),
    exp: Date.now() + TOKEN_VALIDITY_MS,
  };
  return btoa(JSON.stringify(payload));
}

/**
 * Validate a referral token from a URL query parameter.
 * Returns `{ valid: true, payload }` on success or `{ valid: false, error }` on failure.
 */
export function validateReferralToken(token: string): ReferralValidationResult {
  if (!token || token.trim() === '') {
    return {
      valid: false,
      error: 'No referral token provided. You need an invitation link from a verified vendor or brand owner to sign up as a logistics provider.',
    };
  }

  try {
    const decoded = atob(token);
    const payload: ReferralPayload = JSON.parse(decoded);

    if (
      !payload.referrerId ||
      !payload.referrerRole ||
      !payload.type ||
      !payload.exp ||
      !payload.iat
    ) {
      return { valid: false, error: 'Malformed referral token. Please request a fresh invitation link.' };
    }

    if (!['vendor', 'brand'].includes(payload.referrerRole)) {
      return {
        valid: false,
        error: 'Only verified vendors or brand owners can refer logistics providers.',
      };
    }

    if (payload.type !== 'logistics') {
      return { valid: false, error: 'This invitation link is not valid for logistics signup.' };
    }

    if (Date.now() > payload.exp) {
      const expiredAgo = Math.floor((Date.now() - payload.exp) / (1000 * 60 * 60 * 24));
      return {
        valid: false,
        error: `This referral link expired ${expiredAgo > 0 ? `${expiredAgo} day(s) ago` : 'recently'}. Please ask ${payload.referrerName || 'your referrer'} for a new one.`,
      };
    }

    return { valid: true, payload };
  } catch {
    return {
      valid: false,
      error: 'Invalid referral token. The link may be corrupted or tampered with.',
    };
  }
}

/**
 * Build a fully-qualified logistics signup URL containing the referral token.
 * Call this in the browser (requires window.location.origin).
 */
export function buildLogisticsReferralUrl(
  referrerId: string,
  referrerRole: 'vendor' | 'brand',
  referrerName: string
): string {
  const token = generateReferralToken(referrerId, referrerRole, referrerName);
  const origin = typeof window !== 'undefined' ? window.location.origin : '';
  return `${origin}/auth/logistics?ref=${token}`;
}

/**
 * Returns how many days remain before a payload expires.
 */
export function getDaysUntilExpiry(payload: ReferralPayload): number {
  return Math.max(0, Math.floor((payload.exp - Date.now()) / (1000 * 60 * 60 * 24)));
}
